### ISSUE TITLE
Add `id-token` header to `Access-Control-Allow-Headers`

### ISSUE THREAD

**Issue by gvseghbr** [IBCNServices/tengu-charms#11]
The Hauchiwa REST API (`h_api.py`) needs to specify the `id-token` header in the `Access-Control-Allow-Headers`. Browsers who do the preflight (e.g. Chrome) does not allow the usage of headers if they do not appear in the `Access-Control-Allow-Headers` header of the response.

**Comment by gvseghbr** [comment]
Not sure if this will now be taken into account for new Hauchiwas.

**Comment by galgalesh** [comment]
This will not be taken into account until the local charms repository on `h-sojobo` has been synced with this repo. That cannot be done however, since this repo contains (hopefully the last ever) backwards-incompatible patches to enable the CI pipeline. When the pipeline is done, everything will be in sync again, and should stay in sync until infinity..
